In [ ]:
import pandas as pd
import numpy as np


In [ ]:
hr_train = pd.read_csv(r'/content/drive/MyDrive/PGA 23 WD/HR Analytics /train_hr.csv',
                       index_col=0,header = 0)

hr_train.head()

department     region         education gender  \
employee_id                                                          
65438        Sales & Marketing   region_7  Master's & above      f   
65141               Operations  region_22        Bachelor's      m   
7513         Sales & Marketing  region_19        Bachelor's      m   
2542         Sales & Marketing  region_23        Bachelor's      m   
48945               Technology  region_26        Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
hr_train.shape

(54808, 13)

In [ ]:
hr_train.drop("gender",axis=1,inplace=True)
hr_train.shape

(54808, 12)

In [ ]:
hr_train.isnull().sum()

department                 0
region                     0
education               2409
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [ ]:
hr_train["education"].fillna(hr_train["education"].mode()[0],inplace=True)
hr_train["previous_year_rating"].fillna(0,inplace=True)

In [ ]:
hr_train["education"].mode()[0]

"Bachelor's"

In [ ]:
hr_train.isnull().sum()

department              0
region                  0
education               0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [ ]:
hr_train.head()

department     region         education  \
employee_id                                                   
65438        Sales & Marketing   region_7  Master's & above   
65141               Operations  region_22        Bachelor's   
7513         Sales & Marketing  region_19        Bachelor's   
2542         Sales & Marketing  region_23        Bachelor's   
48945               Technology  region_26        Bachelor's   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [ ]:
colname = ['department',
          'region', 'education',
          'recruitment_channel']
colname

['department', 'region', 'education', 'recruitment_channel']

In [ ]:
# For preprocessing the data
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
     hr_train[x]=le.fit_transform(hr_train[x])


In [ ]:
hr_train.head()

department  region  education  recruitment_channel  \
employee_id                                                       
65438                 7      31          2                    2   
65141                 4      14          0                    0   
7513                  7      10          0                    2   
2542                  7      15          0                    0   
48945                 8      18          0                    0   

             no_of_trainings  age  previous_year_rating  length_of_service  \
employee_id                                                                  
65438                      1   35                   5.0                  8   
65141                      1   30                   5.0                  4   
7513                       1   34                   3.0                  7   
2542                       2   39                   1.0                 10   
48945                      1   45                   3.0                  2   

             KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
employee_id                                                               
65438                    1            0                  49            0  
65141                    0            0                  60            0  
7513                     0            0                  50            0  
2542                     0            0                  50            0  
48945                    0            0                  73            0

In [ ]:
X = hr_train.values[:,:-1]
Y = hr_train.values[:,-1]



In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [ ]:
hr_train.dtypes


department                int64
region                    int64
education                 int64
recruitment_channel       int64
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=10)


In [ ]:
import warnings
warnings.filterwarnings("ignore")

# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

print(classifier.coef_)
print(classifier.intercept_)

[[ 0.18504485  0.04224641  0.11767097  0.00992172 -0.09968157 -0.18107998
   0.31198921  0.08063322  0.65714136  0.29332285  0.63146644]]
[-2.87712162]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)



[[14994    70]
 [ 1285    94]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.57      0.07      0.12      1379

    accuracy                           0.92     16443
   macro avg       0.75      0.53      0.54     16443
weighted avg       0.89      0.92      0.89     16443

Accuracy of the model:  0.9175941129964118


# KNN

In [ ]:
"""
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

for K in range(1,31):
    model_KNN = KNeighborsClassifier(K,metric="euclidean")
    model_KNN.fit(X_train, Y_train)
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
"""

'\nfrom sklearn.metrics import accuracy_score\nfrom sklearn.neighbors import KNeighborsClassifier\n\nfor K in range(1,31):\n    model_KNN = KNeighborsClassifier(K,metric="euclidean")\n    model_KNN.fit(X_train, Y_train) \n    Y_pred = model_KNN.predict(X_test)\n    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)\n'

In [ ]:
X_train.shape

(38365, 11)

In [ ]:
hr_train.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [ ]:
#predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=19, metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (1.

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)



[[15029    35]
 [ 1255   124]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.78      0.09      0.16      1379

    accuracy                           0.92     16443
   macro avg       0.85      0.54      0.56     16443
weighted avg       0.91      0.92      0.89     16443

Accuracy of the model:  0.9215471629264733


# SVM

In [ ]:
from sklearn import svm
svc_model=svm.SVC(kernel='rbf',C=1.0,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[15044    20]
 [ 1240   139]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96     15064
         1.0       0.87      0.10      0.18      1379

    accuracy                           0.92     16443
   macro avg       0.90      0.55      0.57     16443
weighted avg       0.92      0.92      0.89     16443

Accuracy of the model:  0.9233716475095786


# Decision Trees

In [ ]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[14096   968]
 [  763   616]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.95      0.94      0.94     15064
         1.0       0.39      0.45      0.42      1379

    accuracy                           0.89     16443
   macro avg       0.67      0.69      0.68     16443
weighted avg       0.90      0.89      0.90     16443

Accuracy of the model:  0.8947272395548258


# Random Forest

In [ ]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[14958   106]
 [  962   417]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.94      0.99      0.97     15064
         1.0       0.80      0.30      0.44      1379

    accuracy                           0.94     16443
   macro avg       0.87      0.65      0.70     16443
weighted avg       0.93      0.94      0.92     16443

Accuracy of the model:  0.9350483488414523


# Upsampling

In [ ]:
hr_train.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [ ]:
from sklearn.utils import resample
# Separate majority and minority classes
df_majority = hr_train[hr_train.is_promoted==0]
df_minority = hr_train[hr_train.is_promoted==1]

# Upsample minority class
df_minority_upsampled = resample(df_minority,
                                 replace=True,     # sample with replacement
                                 n_samples=50140,    # to match majority class
                                 random_state=10) # reproducible results

# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

# Display new class counts
df_upsampled.is_promoted.value_counts()

0    50140
1    50140
Name: is_promoted, dtype: int64

In [ ]:
X = df_upsampled.values[:,:-1]
Y = df_upsampled.values[:,-1]



In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [ ]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=10)


In [ ]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[13955  1060]
 [    0 15069]]
Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96     15015
         1.0       0.93      1.00      0.97     15069

    accuracy                           0.96     30084
   macro avg       0.97      0.96      0.96     30084
weighted avg       0.97      0.96      0.96     30084

Accuracy of the model:  0.9647653237601382


In [ ]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[14410   605]
 [    0 15069]]
Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98     15015
         1.0       0.96      1.00      0.98     15069

    accuracy                           0.98     30084
   macro avg       0.98      0.98      0.98     30084
weighted avg       0.98      0.98      0.98     30084

Accuracy of the model:  0.9798896423347959


In [ ]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

print(classifier.coef_)
print(classifier.intercept_)

[[ 0.21199312  0.01179341  0.086133   -0.00302273 -0.11423911 -0.18998633
   0.3412558   0.06053731  0.83740579  0.5108431   0.72498643]]
[0.03331012]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)



[[10677  4338]
 [ 3986 11083]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.73      0.71      0.72     15015
         1.0       0.72      0.74      0.73     15069

    accuracy                           0.72     30084
   macro avg       0.72      0.72      0.72     30084
weighted avg       0.72      0.72      0.72     30084

Accuracy of the model:  0.7233080707352746


#Down Sampling

In [ ]:
hr_train.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [ ]:
from sklearn.utils import resample
# Separate majority and minority classes
df_majority = hr_train[hr_train.is_promoted==0]
df_minority = hr_train[hr_train.is_promoted==1]

# Upsample minority class
df_majority_upsampled = resample(df_majority,
                                 replace=True,     # sample with replacement
                                 n_samples=10000,    # to match majority class
                                 random_state=10) # reproducible results

# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority_upsampled, df_minority])

# Display new class counts
df_upsampled.is_promoted.value_counts()

0    10000
1     4668
Name: is_promoted, dtype: int64

In [ ]:
X = df_upsampled.values[:,:-1]
Y = df_upsampled.values[:,-1]

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [ ]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=10)


In [ ]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[2544  451]
 [ 508  898]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.83      0.85      0.84      2995
         1.0       0.67      0.64      0.65      1406

    accuracy                           0.78      4401
   macro avg       0.75      0.74      0.75      4401
weighted avg       0.78      0.78      0.78      4401

Accuracy of the model:  0.7820949784139968


In [ ]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[2644  351]
 [ 540  866]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.83      0.88      0.86      2995
         1.0       0.71      0.62      0.66      1406

    accuracy                           0.80      4401
   macro avg       0.77      0.75      0.76      4401
weighted avg       0.79      0.80      0.79      4401

Accuracy of the model:  0.7975460122699386


In [ ]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

print(classifier.coef_)
print(classifier.intercept_)

[[ 0.20875767  0.00557857  0.08167471  0.00978689 -0.09241453 -0.16697167
   0.29861846  0.07601573  0.77388892  0.43781558  0.68269501]]
[-0.97303956]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)



[[2629  366]
 [ 814  592]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.76      0.88      0.82      2995
         1.0       0.62      0.42      0.50      1406

    accuracy                           0.73      4401
   macro avg       0.69      0.65      0.66      4401
weighted avg       0.72      0.73      0.72      4401

Accuracy of the model:  0.7318791183821859


#Smote(synthetic minority over sampling technique)

This technique allow us to up-sample the minority calss observations to reach the level of the majority class by creating synthetic samples
similar to the existing samples it helps us overcome the over-fitting probelm that happens in case of up-sampling the synthetic samples are created by taking the average values of k-radomly selected datapoints



In [ ]:
X = hr_train.values[:,:-1]
Y = hr_train.values[:,-1]



In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X)

X = scaler.transform(X)
#print(X)

In [ ]:
hr_train.dtypes


department                int64
region                    int64
education                 int64
recruitment_channel       int64
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
                                                    random_state=10)


In [ ]:
pip install imblearn

In [ ]:
print("Before OverSampling, counts of label '1': ", (sum(Y_train == 1)))
print("Before OverSampling, counts of label '0': ", (sum(Y_train == 0)))

# import SMOTE from imblearn library
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 10,k_neighbors=5)
X_train_res, Y_train_res = sm.fit_resample(X_train, Y_train)

print('After OverSampling, the shape of train_X: ', (X_train_res.shape))
print('After OverSampling, the shape of train_y: ', (Y_train_res.shape))

print("After OverSampling, counts of label '1': ", (sum(Y_train_res == 1)))
print("After OverSampling, counts of label '0': ", (sum(Y_train_res == 0)))

Before OverSampling, counts of label '1':  3289
Before OverSampling, counts of label '0':  35076
After OverSampling, the shape of train_X:  (70152, 11)
After OverSampling, the shape of train_y:  (70152,)
After OverSampling, counts of label '1':  35076
After OverSampling, counts of label '0':  35076


In [ ]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train_res,Y_train_res)
Y_pred=model_DecisionTree.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[13940  1124]
 [  724   655]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.95      0.93      0.94     15064
         1.0       0.37      0.47      0.41      1379

    accuracy                           0.89     16443
   macro avg       0.66      0.70      0.68     16443
weighted avg       0.90      0.89      0.89     16443

Accuracy of the model:  0.8876117496807152


In [ ]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train_res,Y_train_res)

Y_pred=model_RandomForest.predict(X_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)


[[14676   388]
 [  848   531]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.95      0.97      0.96     15064
         1.0       0.58      0.39      0.46      1379

    accuracy                           0.92     16443
   macro avg       0.76      0.68      0.71     16443
weighted avg       0.91      0.92      0.92     16443

Accuracy of the model:  0.9248312351760628


In [ ]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train_res,Y_train_res)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

print(classifier.coef_)
print(classifier.intercept_)

[[ 0.20050683  0.02040044  0.12156822  0.00324611 -0.14920414 -0.2686338
   0.3832129   0.0710084   0.80593331  0.3137575   0.70085851]]
[-0.60766097]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,\
classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)



[[10662  4402]
 [  407   972]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.96      0.71      0.82     15064
         1.0       0.18      0.70      0.29      1379

    accuracy                           0.71     16443
   macro avg       0.57      0.71      0.55     16443
weighted avg       0.90      0.71      0.77     16443

Accuracy of the model:  0.7075351213282248
